name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        submodules: recursive

    - name: Install OpenSSL (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y libssl-dev

    - name: Install OpenSSL (macOS)
      if: runner.os == 'macOS'
      run: brew install openssl

    - name: Install OpenSSL (Windows)
      if: runner.os == 'Windows'
      run: choco install openssl

    - name: Build and Run Tests
      run: bash ./b.sh test release
      
    - name: Run Analyze (Linux Only)
      if: runner.os == 'Linux'
      run:  ln -sf "build/release/compile_commands.json" compile_commands.json && bash ./b.sh analyze